"""Script creator for V.E.R.A. — generates and saves new automation scripts."""

import os
import re
from pathlib import Path
from utils.os_detector import get_current_os, get_script_extension
from utils.logger import get_logger

logger = get_logger("vera.engine")


class ScriptCreator:
    """Creates new automation scripts from LLM-generated code and saves them."""

    def __init__(self, custom_scripts_dir: str | Path):
        self.custom_dir = Path(custom_scripts_dir)
        self.custom_dir.mkdir(parents=True, exist_ok=True)
        self.current_os = get_current_os()
        self.script_extension = get_script_extension()

    def create_script(self, name: str, code: str, description: str = "") -> dict:
        safe_name = self._sanitize_name(name)
        if not safe_name:
            return {"name": name, "path": None, "description": description, "success": False, "error": "Invalid script name"}

        file_path = self.custom_dir / f"{safe_name}{self.script_extension}"
        
        # Strip markdown formatting if the LLM included it
        cleaned_code = self._clean_code(code)
        code_with_header = self._add_header(cleaned_code, description)

        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code_with_header)
            if self.current_os in ("linux", "macos"):
                os.chmod(file_path, 0o755)
            logger.info(f"Created new script: {file_path}")
            return {"name": safe_name, "path": str(file_path), "description": description, "success": True}
        except Exception as e:
            logger.error(f"Failed to create script {safe_name}: {e}")
            return {"name": safe_name, "path": None, "description": description, "success": False, "error": str(e)}

    def _sanitize_name(self, name: str) -> str:
        safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in name)
        safe = safe.strip("_-")
        return safe[:100] if len(safe) >= 2 else ""

    def _clean_code(self, code: str) -> str:
        """Strip markdown code block syntax if present."""
        code = code.strip()
        # Remove starting ```[lang] and ending ```
        if code.startswith("```"):
            # Find the first newline after ```
            first_newline = code.find("\n")
            if first_newline != -1:
                code = code[first_newline+1:]
        if code.endswith("```"):
            code = code[:-3]
        return code.strip()

    def _add_header(self, code: str, description: str) -> str:
        if self.current_os == "windows":
            header = f"REM {description}\nREM Generated by V.E.R.A.\n\n"
        else:
            header = f"#!/bin/bash\n# {description}\n# Generated by V.E.R.A.\n\n"
        return header + code

    def list_custom_scripts(self) -> list[dict]:
        scripts = []
        for file in self.custom_dir.iterdir():
            if file.is_file() and file.suffix in (".bat", ".sh", ".cmd", ".ps1"):
                scripts.append({"name": file.stem, "path": str(file)})
        return scripts
