REM Generates a Windows battery report and saves it to the Desktop as battery-report.html
REM Generated by V.E.R.A.

@echo off
REM Generate battery report and save to Desktop
powercfg /batteryreport /output "C:\Users\manik\OneDrive\Desktop\battery-report.html"
echo Battery report generated and saved to Desktop as battery-report.html