REM Extracts key battery metrics (design capacity, full charge capacity, cycle count) from battery-report.html and calculates degradation percentage.
REM Generated by V.E.R.A.

@echo off
REM Parse battery-report.html for key metrics
set "report_path=C:\Users\manik\OneDrive\Desktop\battery-report.html"
set "temp_file=%TEMP%\battery_metrics.txt"

REM Extract Design Capacity (original max capacity)
findstr /C:"DESIGN CAPACITY" "%report_path%" > "%temp_file%"
for /f "tokens=2 delims=:" %%A in ('findstr /C:"DESIGN CAPACITY" "%report_path%"') do (
    for /f "tokens=1 delims=<" %%B in ("%%A") do set "design_capacity=%%B"
)

REM Extract Full Charge Capacity (current max capacity)
findstr /C:"FULL CHARGE CAPACITY" "%report_path%" >> "%temp_file%"
for /f "tokens=2 delims=:" %%A in ('findstr /C:"FULL CHARGE CAPACITY" "%report_path%"') do (
    for /f "tokens=1 delims=<" %%B in ("%%A") do set "full_capacity=%%B"
)

REM Extract Cycle Count
findstr /C:"CYCLE COUNT" "%report_path%" >> "%temp_file%"
for /f "tokens=2 delims=:" %%A in ('findstr /C:"CYCLE COUNT" "%report_path%"') do (
    for /f "tokens=1 delims=<" %%B in ("%%A") do set "cycle_count=%%B"
)

REM Calculate degradation percentage
set /a degradation=100 - (%full_capacity% * 100 / %design_capacity%)

REM Output results
echo Design Capacity: %design_capacity% mWh
echo Full Charge Capacity: %full_capacity% mWh
echo Cycle Count: %cycle_count%
echo Battery Degradation: %degradation%%%

REM Save results to desktop
echo Battery Report Summary > "C:\Users\manik\OneDrive\Desktop\battery_metrics.txt"
echo. >> "C:\Users\manik\OneDrive\Desktop\battery_metrics.txt"
echo Design Capacity: %design_capacity% mWh >> "C:\Users\manik\OneDrive\Desktop\battery_metrics.txt"
echo Full Charge Capacity: %full_capacity% mWh >> "C:\Users\manik\OneDrive\Desktop\battery_metrics.txt"
echo Cycle Count: %cycle_count% >> "C:\Users\manik\OneDrive\Desktop\battery_metrics.txt"
echo Battery Degradation: %degradation%%% >> "C:\Users\manik\OneDrive\Desktop\battery_metrics.txt"

del "%temp_file%"
echo Battery metrics saved to Desktop\battery_metrics.txt.